"""Render and manage the single `llm.service` user unit."""
from __future__ import annotations

import os
import subprocess as _subprocess
from pathlib import Path
from typing import Any, Callable

_UNIT_TEMPLATE = """\
# AUTO-GENERATED by `llm serve`. Edit will be overwritten on next `llm serve --systemd`.
[Unit]
Description=LocalLLM service (config: {config_id})
After=network.target

[Service]
Type=simple
ExecStart=%h/.local/bin/llm serve {config_id} --foreground-from-supervisor
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
"""


def desired_unit_text(config_id: str) -> str:
    return _UNIT_TEMPLATE.format(config_id=config_id)


def unit_path() -> Path:
    """Resolve ~/.config/systemd/user/llm.service honoring $XDG_CONFIG_HOME."""
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg) if xdg else Path.home() / ".config"
    return base / "systemd" / "user" / "llm.service"


def write_if_different(text: str) -> bool:
    """Write unit text to disk only if it differs. Returns True on change."""
    path = unit_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def _default_runner(
    cmd: list[str], **kw: Any
) -> _subprocess.CompletedProcess[str]:
    return _subprocess.run(
        cmd, capture_output=True, text=True, timeout=20, **kw
    )


def daemon_reload(*, runner: Callable[..., Any] = _default_runner) -> None:
    r = runner(["systemctl", "--user", "daemon-reload"])
    if r.returncode != 0:
        raise RuntimeError(
            f"daemon-reload failed (rc={r.returncode}): {r.stderr!r}"
        )


def restart_unit(unit: str, *, runner: Callable[..., Any] = _default_runner) -> None:
    r = runner(["systemctl", "--user", "restart", unit])
    if r.returncode != 0:
        raise RuntimeError(
            f"restart {unit} failed (rc={r.returncode}): {r.stderr!r}"
        )


def stop_unit(unit: str, *, runner: Callable[..., Any] = _default_runner) -> None:
    r = runner(["systemctl", "--user", "stop", unit])
    if r.returncode != 0:
        raise RuntimeError(f"stop {unit} failed (rc={r.returncode}): {r.stderr!r}")


def is_active(unit: str, *, runner: Callable[..., Any] = _default_runner) -> bool:
    try:
        r = runner(["systemctl", "--user", "is-active", unit])
    except (FileNotFoundError, _subprocess.TimeoutExpired):
        return False
    return (r.stdout or "").strip() == "active"
