"""Render and manage the single `llm.service` user unit."""
from __future__ import annotations

_UNIT_TEMPLATE = """\
# AUTO-GENERATED by `llm serve`. Edit will be overwritten on next `llm serve --systemd`.
[Unit]
Description=LocalLLM service (config: {config_id})
After=network.target

[Service]
Type=simple
ExecStart=%h/.local/bin/llm serve {config_id} --foreground-from-supervisor
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
"""


def desired_unit_text(config_id: str) -> str:
    return _UNIT_TEMPLATE.format(config_id=config_id)
